USE [master]
GO

/****** Object:  Database [BibliotekaDb]    Script Date: 23.7.2018. 01.32.43 ******/
CREATE DATABASE [BibliotekaDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BibliotekaDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BibliotekaDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BibliotekaDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BibliotekaDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BibliotekaDb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BibliotekaDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BibliotekaDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BibliotekaDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BibliotekaDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BibliotekaDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BibliotekaDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [BibliotekaDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BibliotekaDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BibliotekaDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BibliotekaDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BibliotekaDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BibliotekaDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BibliotekaDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BibliotekaDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BibliotekaDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BibliotekaDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BibliotekaDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BibliotekaDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BibliotekaDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BibliotekaDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BibliotekaDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BibliotekaDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BibliotekaDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BibliotekaDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BibliotekaDb] SET  MULTI_USER 
GO

ALTER DATABASE [BibliotekaDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BibliotekaDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BibliotekaDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BibliotekaDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BibliotekaDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BibliotekaDb] SET QUERY_STORE = OFF
GO

USE [BibliotekaDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BibliotekaDb] SET  READ_WRITE 
GO

